### ISSUE TITLE
Implement Topological Operators (Spatial) for Temporal Types

### ISSUE THREAD

**Issue by chaitan94** [adonmo/meos#25]
Invalid operations should throw accordingly

Refer MobilityDB docs for more information: https://docs.mobilitydb.com/MobilityDB/master/ch05s17.html

### Todo Checklist
  - [ ] contains({geo, tgeompoint}, {geo, tgeompoint}): boolean
  - [ ] containsproperly({geo, tgeompoint}, {geo, tgeompoint}): boolean
  - [ ] covers({geo, tpoint}, {geo, tpoint}): boolean
  - [ ] coveredby({geo, tpoint}, {geo, tpoint}): boolean
  - [ ] crosses({geo, tgeompoint}, {geo, tgeompoint}): boolean
  - [ ] disjoint({geo, tgeompoint}, {geo, tgeompoint}): boolean
  - [ ] equals({geo, tgeompoint}, {geo, tgeompoint}): boolean
  - [ ] intersects({geo, tpoint}, {geo, tpoint}): boolean
  - [ ] overlaps({geo, tgeompoint}, {geo, tgeompoint}): boolean
  - [ ] touches({geo, tgeompoint}, {geo, tgeompoint}): boolean
  - [ ] within({geo, tgeompoint}, {geo, tgeompoint}): boolean
  - [ ] dwithin({geo, tpoint}, {geo, tpoint}, double): boolean
  - [ ] relate({geo, tgeompoint}, {geo, tgeompoint}): text
  - [ ] relate({geo, tgeompoint}, {geo, tgeompoint}, text): boolean
