### ISSUE TITLE
Implement Topological Operators (Spatiotemporal) for Temporal Types

### ISSUE THREAD

**Issue by chaitan94** [adonmo/meos#26]
Invalid operations should throw accordingly

Refer MobilityDB docs for more information: https://docs.mobilitydb.com/MobilityDB/master/ch05s17.html

### Todo Checklist
  - [ ] tcontains({geo, tgeompoint}, {geo, tgeompoint}): tbool
  - [ ] tcovers({geo, tpoint}, {geo, tpoint}): tbool
  - [ ] tcoveredby({geo, tpoint}, {geo, tpoint}): tbool
  - [ ] tdisjoint({geo, tgeompoint}, {geo, tgeompoint}): tbool
  - [ ] tequals({point, tgeompoint}, {point, tgeompoint}): tbool
  - [ ] tintersects({geo, tpoint}, {geo, tpoint}): tbool
  - [ ] ttouches({geo, tgeompoint}, {geo, tgeompoint}): tbool
  - [ ] twithin({geo, tgeompoint}, {geo, tgeompoint}): tbool
  - [ ] tdwithin({geo, tpoint}, {geo, tpoint}, double): tbool
  - [ ] trelate({geo, tgeompoint}, {geo, tgeompoint}, text): tbool
  - [ ] trelate({geo, tgeompoint}, {geo, tgeompoint}): ttext
