### ISSUE TITLE
Implement Topological Operators for Time Types

### ISSUE THREAD

**Issue by chaitan94** [adonmo/meos#27]
• <<: Is the first numeric or range value strictly left of the second one?
• >>: Is the first numeric or range value strictly right of the second one?
• &<: Is the first numeric or range value not to the right of the second one?
• &>: Is the first numeric or range value not to the left of the second one?
• -|-: Is the first numeric or range value adjacent to the second one?
• <<#: Is the first time value strictly before the second one?
• #>>: Is the first time value strictly after the second one?
• &<#: Is the first time value not after the second one?
• #&>: Is the first time value not before the second one?

Invalid operations should throw accordingly

Refer MobilityDB docs for more information: https://docs.mobilitydb.com/MobilityDB/master/ch02.html#time_relpos_operators

### Todo Checklist
  - [ ] always_strictly_less_than
  - [ ] always_strictly_greater_than
  - [ ] never_greater_than
  - [ ] never_less_than
  - [ ] adjacent_to
  - [ ] always_before
  - [ ] always_after
  - [ ] never_after
  - [ ] never_before
