### ISSUE TITLE
Implement Topological Operators for Box Types

### ISSUE THREAD

**Issue by chaitan94** [adonmo/meos#29]
• <<: Are the X values of the first bounding box strictly less than those of the second one?
• >>: Are the X values of the first bounding box strictly greater than those of the second one?
• &<: Are the X values of the first bounding box not greater than those of the second one?
• &>: Are the X values of the first bounding box not less than those of the second one?
• <<: Are the X values of the first bounding box strictly to the left of those of the second one?
• >>: Are the X values of the first bounding box strictly to the right of those of the second one?
• &<: Are the X values of the first bounding box not to the right of those of the second one?
• &>: Are the X values of the first bounding box not to the left of those of the second one?
• <<|: Are the Y values of the first bounding box strictly below of those of the second one?
• |>>: Are the Y values of the first bounding box strictly above of those of the second one?
• &<|: Are the Y values of the first bounding box not above of those of the second one?
• |&>: Are the Y values of the first bounding box not below of those of the second one?
• <</: Are the Z values of the first bounding box strictly in front of those of the second one?
• />>: Are the Z values of the first bounding box strictly back of those of the second one?
• &</: Are the Z values of the first bounding box not back of those of the second one?
• /&>: Are the Z values of the first bounding box not in front of those of the second one?
• <<#: Are the T values of the first bounding box strictly before those of the second one?
• #>>: Are the T values of the first bounding box strictly after those of the second one?
• &<#: Are the T values of the first bounding box not after those of the second one?
• #&>: Are the T values of the first bounding box not before those of the second one?

Invalid operations should throw accordingly

Refer MobilityDB docs for more information: https://docs.mobilitydb.com/MobilityDB/master/ch04s10.html

### Todo Checklist
  - [ ] always_strictly_less_than ("<<")
  - [ ] always_strictly_greater_than (">>")
  - [ ] never_greater_than ("&<")
  - [ ] never_less_than ("&>")
  - [ ] strictly_to_left ("<<")
  - [ ] strictly_to_right (">>")
  - [ ] not_to_the_right_of ("&<")
  - [ ] not_to_the_left_of ("&>")
  - [ ] strictly_below ("<<|")
  - [ ] strictly_above ("|>>")
  - [ ] does_not_extend_to_left ("&>")
  - [ ] does_not_extend_to_right ("&<")
  - [ ] does_not_extend_below ("&<|")
  - [ ] does_not_extend_above ("|&>")
  - [ ] strictly_in_front ("<</")
  - [ ] strictly_in_back ("/>>")
  - [ ] does_not_extend_in_front ("&</")
  - [ ] does_not_extend_in_back ("/&>")
  - [ ] always_before ("<<#")
  - [ ] always_after ("#>>")
  - [ ] never_after ("&<#")
  - [ ] never_before ("#&>")
